In [1]:
# print function
print("Hello World!")

Hello World!


In [2]:
# libraries
import random
for i in range(5):
    print(random.randint(10,99))

46
40
71
49
93


In [3]:
# indentation
x = 0

while x < 10:
    if x % 2 == 0:
        print(x)
    x += 1

print('done.')

0
2
4
6
8
done.


In [5]:
# dynamic typing

var = 5
print(var)
print(type(var))

var = 'spam'
print(var)
print(type(var))

5
<class 'int'>
spam
<class 'str'>


In [9]:
# strings

mystring = 'ham and eggs'
print(mystring[0:4]) # note that the first index is inclusive and the second index is exclusive
print(mystring.find('and')) # 'and' starts at index 4
print(mystring.split(' '))

ham 
4
['ham', 'and', 'eggs']


In [12]:
# lists

mylist = [1, 2]
mylist.append("three")

print(mylist)

[1, 2, 'three']


In [15]:
# tuples

tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')

try:
    tup1[0] = 100;
except TypeError:
    print('See why this returns an error?')
    # This prints because tuples can't be modified


tup3 = tup1 + tup2 # this concatenates the two tuples
print(tup3)
print(len(tup3))
for x in tup3: print(x)

See why this returns an error?
(12, 34.56, 'abc', 'xyz')
4
12
34.56
abc
xyz


In [17]:
# dictionaries
numbers = {'one': 1, 'two': 2, 'three': 3, 'four': 4 }
print(numbers['one'])
del numbers['one']  # Remove an entry from the dictionary

try:
    print(numbers['one'])
except KeyError:
    print("This shouldn't work, since we deleted numbers['one'] above")

print(numbers)
print(numbers.keys())
print(numbers.values())

1
This shouldn't work, since we deleted numbers['one'] above
{'two': 2, 'three': 3, 'four': 4}
dict_keys(['two', 'three', 'four'])
dict_values([2, 3, 4])


In [20]:
# name binding

# mutable objects
a = [1, 2]
b = a
print(b, a)
b.append(3)
print(a) # a is also modified

# immutable objects
a = 1
b = a
print(b, a)
b = b + 1
print(a)
print(b)

[1, 2] [1, 2]
[1, 2, 3]
1 1
1
2


In [4]:
# control flow
age = 22

if age < 13:
    print('kid')
elif age < 18:
    print('teen')
else:
    print('adult')

adult


In [6]:
# control flow
for i in range(5):
    pass

for i in [0, 1, 2, 3, 4]:
    if i > 5:
        break
else:
    print('Python supports the else keyword for for-loops, which execute if the loop completes without breaking')

Python supports the else keyword for for-loops, which execute if the loop completes without breaking


In [7]:
# control flow

x = 1024

while x > 1:
    x = x / 2
    if (x % 10) != 2:
        continue
    print(x)

512.0
32.0
2.0


In [10]:
# Functions

def example_func(s="hello!"):
    print(s)

example_func("goodbye!")
example_func() # This is equivalent to exapmle_func("hello!") since we give the parameter s a default value of "hello!"

goodbye!
hello!


In [12]:
# Classes

import math

class Vector2:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def len(self):
        return math.sqrt(self.x ** 2 +
                         self.y ** 2)

    _DoNotTouch = 10


v = Vector2(3, 4)
print("({},{}):".format(v.x, v.y), \
      "len = {}".format(v.len()))

(3,4): len = 5.0


In [16]:
# Fibonacci

from typing import List
# parameters: num -> int, numbers of fibonacci's to generate
# returns:    sequence -> list, generated fibonacci sequence
def fibonacci(num: int) -> List[int]:
    sequence = [0, 1]  # Initialize with first two Fibonacci numbers
    
    while len(sequence) < num:
        sequence.append(sequence[-1] + sequence[-2])  # Add sum of last two numbers
        
    return sequence

assert(fibonacci(10)[9] == 34)

In [18]:
# Linear ALgebra Refresh

A = [[1,2,3],[4,5,6]]      # Shape=(2,3)
B = [[7,8],[9,10],[11,12]] # Shape=(3,2)

In [24]:
# NumPy Basics

import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a.shape)            # Prints "(3,)" i.e length 
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [25]:
# NumPy Custom Functions Create Arrays

import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.6818447  0.73394409]
 [0.05975764 0.85026094]]


In [3]:
# NumPy Array Operations

import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce an array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print("ADDITION")
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce an array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print("SUBTRACTION")
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce an array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print("MULTIPLICATION")
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce an array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print("DIVISON")
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces an array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("SQUARE ROOT:")
print(np.sqrt(x))

# Reshape; changes the dimensions of a matrix
# [[ 1.  2.  3.  4.]]
print("CHANGE DIMENSIONS")
x2 = np.reshape(x, [1, 4])
print(x2)

# Max; returns the value of the largest element
# 4.0
print("MAX")
print(np.max(x2))

# Argmax; returns the index of the largest element
# 3
print("INDEX OF LARGESTS NUMBER")
print(np.argmax(x2))

ADDITION
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
SUBTRACTION
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
MULTIPLICATION
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
DIVISON
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
SQUARE ROOT:
[[1.         1.41421356]
 [1.73205081 2.        ]]
CHANGE DIMENSIONS
[[1. 2. 3. 4.]]
MAX
4.0
INDEX OF LARGESTS NUMBER
3


In [5]:
# Matrix Multiplication

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print("DOT OF 2 1D ARRAYS")
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print("DOT OF 1 1D and 1 2D ARRAY")
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# Matmul and dot are the same for 2D operations, but differ when we increase dimensionalities.
# [[19 22]
#  [43 50]]
print("DOT OF 2 2D ARRAYS")
print(x.dot(y))
print(np.matmul(x, y))

DOT OF 2 1D ARRAYS
219
219
DOT OF 1 1D and 1 2D ARRAY
[29 67]
[29 67]
DOT OF 2 2D ARRAYS
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [7]:
# Broadcasting

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #shape (4,3)
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print("ADD 1D to each row of 4 row, 3 col ARRAY")
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

ADD 1D to each row of 4 row, 3 col ARRAY
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [12]:
# Multiple Dimensional Matrix Multiplication

import numpy as np

# Let's say we have the following matrix A
A = np.random.random((50, 100, 20))
print("MATRIX A:")
print(A)
# We can imagine A as 50 instances of (100,20) matrices.
# We have the following matrix B
B = np.random.random((20,40))
print("MATRIX B:")
print(B)
# We want to multiply each (100,20) instance of A by B, we can do this because the dimensions match up: 20 = 20
print("A SHAPE:", A.shape)
print("B SHAPE:", B.shape)
print("MATRIX PRODUCT")
print(np.dot(A,B).shape)
# should be (50, 100, 40), each of the 50 (100,20) is multiplied by (20,40) matrix to yield (100, 40)

MATRIX A:
[[[0.85025006 0.17394721 0.40823583 ... 0.94448564 0.18507596 0.88095711]
  [0.77091989 0.62496049 0.29698628 ... 0.43378439 0.4209403  0.19970805]
  [0.95015678 0.01136454 0.82669187 ... 0.132062   0.32159421 0.90748795]
  ...
  [0.35318923 0.15844691 0.62946281 ... 0.72840693 0.5130889  0.93945742]
  [0.69835319 0.18292356 0.20305363 ... 0.31868258 0.27697645 0.58649736]
  [0.92825672 0.42037014 0.17549116 ... 0.06268248 0.38595876 0.36827328]]

 [[0.78313207 0.96208484 0.5242641  ... 0.55000789 0.44962252 0.70054343]
  [0.59479808 0.99109358 0.08374849 ... 0.29527898 0.85074942 0.4630729 ]
  [0.26699943 0.03304657 0.63751853 ... 0.81057848 0.27003446 0.59809446]
  ...
  [0.62259568 0.74789368 0.81501758 ... 0.14675594 0.48230695 0.24603853]
  [0.58603333 0.50147704 0.21884085 ... 0.87746541 0.00180008 0.15525638]
  [0.22986409 0.6157103  0.81281001 ... 0.3168635  0.2408493  0.26035818]]

 [[0.66590124 0.44172497 0.45746558 ... 0.53678279 0.59621796 0.46911125]
  [0.7317273

In [15]:
import numpy as np
A = np.array([[0,1,2],[3,4,5]]) # shape (2,3)
B = np.array([[1,1,1]]) # shape (1,3)
C = np.array([[-1,-1,-1],[1,1,1]]) # shape (2,3)

# TODO
# Create matrix "D" as A - B using broadcasting
D = np.subtract(A, B) # D will have shape(2, 3)
# Create matrix "E" with shape (3,2) by reshaping C
E = np.reshape(C, (3,2))
# Create matrix "F" with shape (2,2) by matrix multiplying "D" by "E"
# D has shape (2,3)
# E has shape (3,2)
# F wil have shape (2, 2)
F = np.matmul(D, E)

assert(np.all(D == [[-1,0,1],[2,3,4]]))
assert(np.all(E == [[-1,-1],[-1,1],[1,1]]))
assert(np.all(F == [[2,2],[-1,5]]))

[[ 2  2]
 [-1  5]]
